import pg from 'pg'
const c = new pg.Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } })
await c.connect()
const u = await c.query('SELECT username, role, nama FROM users ORDER BY id')
console.log('users:', JSON.stringify(u.rows))
const p = await c.query('SELECT COUNT(*) FROM pekerja')
console.log('pekerja:', p.rows[0].count)
const m = await c.query('SELECT nama_model, ongkos_kerja FROM tipe_sepatu ORDER BY id_sepatu')
console.log('model:', JSON.stringify(m.rows))
const uk = await c.query('SELECT COUNT(*) FROM master_ukuran')
console.log('ukuran:', uk.rows[0].count)
const po = await c.query('SELECT no_po FROM master_po')
console.log('po:', JSON.stringify(po.rows))
const v = await c.query('SELECT * FROM v_rekap_gaji')
console.log('v_rekap_gaji rows:', v.rows.length)
const vv = await c.query('SELECT * FROM v_total_per_produksi')
console.log('v_total head:', JSON.stringify(vv.rows[0] ?? null))
await c.end()